Fix nil error when running rake ember:install
```
TypeError: no implicit conversion of nil into String
```

Ruby 2.3.0
Node v5.0.0
ember-cli-rails 0.7.0

I didn't have bower installed, so adding path.to_s allowed the code to tell me I needed to install bower.